server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sport-team-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true